### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by bluecmd** [ANSSI-FR/ultrablue#16]
Hi!

I watched your talk on OSFC 2022 and I would like to give this project a go. However, I have basically zero experience compiling Android apps. Thus I was wondering if you have any plans on releasing binaries for the clients and server?

Ideally being able to just install ultrablue through `dnf` and Google Play Store would be extremely nice.

Thanks for your work!

**Comment by kerneis-anssi** [comment]
Sorry for the (very) long delay and thanks a lot for the feedback. We're resumed work on Ultrablue this month and should make a beta release for easier testing next week.

**Comment by kerneis-anssi** [comment]
We made a release for the FOSDEM presentation today: https://github.com/ANSSI-FR/ultrablue/releases/tag/fosdem-2023

Please let us know if it doesn't work. We'll have a follow-up release with essentially the same code but better instructions in the next week.
